# This is a basic workflow to help you get started with Actions
name: 'Linux Build'

on:
  create:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Set Version Number
        run: |
          npx replace-in-files-cli --string="##version##" --replacement="${{ steps.tagName.outputs.tag }}" "src/**/*" "scripts/**/*"
      - run: node "./scripts/version.script.js"
      - name: Check lint
        run: npm run lint
      - name: Build the app
        run: npm run electron:linux
      - uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: release/*.AppImage
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server01.codext.de
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: released/
          server-dir: ./linux/
